#!/bin/sh
echo checking lines exceeding 73 cols
echo note: total is allowed to exceed 73 cols
find pilang -type f | awk '{if (!match($0, "yacc.md")) print $0}' \
     | xargs cat | awk '{if (length > 73) print $0}'
echo checking lines containing tab keys, makefiles ignored automatically
find pilang -type f | awk '{if (!match($0, "makefile")) print $0}' \
     | xargs cat | awk '{if (match($0, "\t")) print $0}'

echo -- example --
echo and this line contains	tab key
echo this line exceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeds 73 cols
